//#define APPLICATION_VERSION_DLL
//#define _DEBUG

#define APPLICATION_FILEVERSION     3,0,8
#define APPLICATION_PRODUCTVERSION  3,0,8
#define APPLICATION_FILEFLAGSMASK   0x0L

#define APPLICATION_STR_COMPANY_NAME        "Company"
#define APPLICATION_STR_FILE_DESCRIPTION    "Desc"
#define APPLICATION_STR_FILE_VERSION        "3.0.8"
#define APPLICATION_STR_INTERNAL_NAME       "aa"
#define APPLICATION_STR_ORIGINAL_COPYRIGHT  "bb"
#define APPLICATION_STR_LEGAL_COPYRIGHT     "cc"
#define APPLICATION_STR_ORIGINAL_FILENAME   "dd"
#define APPLICATION_STR_PRODUCT_NAME        "ee"
#define APPLICATION_STR_PRODUCT_VERSION     "1.0.1.0"
